#!/bin/sh
LANG_SHORT=${LANG%%_*}
[ -z "$LANG_SHORT" ] && LANG_SHORT='en'
IS_SOURCE=$(printf "%s" $0 | awk '/^(\.|\/)/ {print 1}')
msg () {
    correct='./install-sh [--python | --sh-posix]'
    case "$LANG_SHORT" in
        es)
        case "$1" in
            option) printf "Seleccione la versión o \033[1mC\033[0m para cancelar: " ;;
            0) printf "\033[1m¡Instalado correctamente!\033[0m" ;;
            1) printf 'Instalación cancelada.' ;;
            2) printf 'Uso incorrecto. %s' "$correct" ;;
            3) printf 'Opción incorrecta. %s' "$correct" ;;
            4) printf '\033[1msudo\033[0m no encontrado. Ejecute este script como root.' ;;
            5) printf 'Ejecute \033[7mrehash\033[0m o reinicie la terminal.' ;;
            6) printf 'Error durante la copia del archivo.' ;;
        esac ;;
        *)
        case "$1" in
            option) printf "Choose a version or \033[1mC\033[0m to cancel: " ;;
            0) printf "\033[1mSuccessfully installed!\033[0m" ;;
            1) printf 'Installation cancelled.' ;;
            2) printf 'Invalid usage. %s' "$correct" ;;
            3) printf 'Incorrect option. %s' "$correct" ;;
            4) printf '\033[1msudo\033[0m command not found. Run this script as root.' ;;
            5) printf 'Run \033[7mrehash\033[0m or restart the terminal.' ;;
            6) printf 'Error copying file.' ;;
        esac ;;
    esac
    if [ "$1" = option ]; then
        return 0
    else
        return $1
    fi
}

OPTION="${1:-}"
o=''
case "$#" in
    0)
    while [ -z "$o" ]; do
        printf '\033[1m1\033[0m.- Python\n'
        printf '\033[1m2\033[0m.- Shell (POSIX)\n'
        msg option
        IFS= read -r o || o="$(msg 1)"
        case "$o" in
            1) OPTION='--python' ;;
            2) OPTION='--sh-posix' ;;
            C|c) OPTION=C; o="$(msg 1)"; printf "%s\n" "$o" ;;
            *) o='' ;;
        esac
    done
;;
    1) ;;
    *) OPTION=C; o="$(msg 2)"; printf "%s\n" "$o"; [ -n "$IS_SOURCE" ] && exit 2 ;;
esac
[ "$OPTION" != C ] && o=''
case "$OPTION" in
    -py|--python) file='apt_trixie.py' ;;
    -sh|--sh-posix) file='apt_trixie.sh' ;;
    C|c) ;;
    *) o="$(msg 3)"; printf "%s\n" "$o"; [ -n "$IS_SOURCE" ] && exit 3 ;;
esac

if [ "$(id -u)" -gt 0 ]; then
    copy_cmd='sudo cp'
    chmod_cmd='sudo chmod'
fi
to='/usr/local/bin/apt'

if [ -z "$o" ]; then
    if [ "$(id -u)" -eq 0 ]; then
        cp "$file" "$to" && chmod +x "$to"
        ret="$?"
    elif command -v sudo >/dev/null 2>&1; then
        sudo sh -c "cp '$file' '$to' && chmod +x '$to'"
        ret="$?"
    else
        o="$(msg 4)"; printf "%s\n" "$o"; [ -n "$IS_SOURCE" ] && exit 4
    fi
    if [ "$ret" -eq 0 ]; then
        o="$(msg 0)"; printf "%s\n" "$o"
        hash -r
        if [ "${SHELL##*/}" = zsh ] && [ -n "$IS_SOURCE" ]; then
            o="$(msg 5)"; printf "%s\n" "$o"; [ -n "$IS_SOURCE" ] && exit 0
        fi
    else
        o="$(msg 6)"; printf "%s\n" "$o"; [ -n "$IS_SOURCE" ] && exit 6
    fi
fi
